# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protocoloAtt_pb2 as protocoloAtt__pb2


class ServicioStub(object):
  """----------------------------------------------------

  service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ConsultarDestino = channel.unary_unary(
        '/Servicio/ConsultarDestino',
        request_serializer=protocoloAtt__pb2.NuevoAvionRequest.SerializeToString,
        response_deserializer=protocoloAtt__pb2.NuevoAvionResponse.FromString,
        )
    self.PedirPermiso = channel.unary_unary(
        '/Servicio/PedirPermiso',
        request_serializer=protocoloAtt__pb2.PermisoRequest.SerializeToString,
        response_deserializer=protocoloAtt__pb2.PermisoResponse.FromString,
        )
    self.PedirInstrucciones = channel.unary_unary(
        '/Servicio/PedirInstrucciones',
        request_serializer=protocoloAtt__pb2.InstruccionesRequest.SerializeToString,
        response_deserializer=protocoloAtt__pb2.InstruccionesResponse.FromString,
        )
    self.VerificarCola = channel.unary_unary(
        '/Servicio/VerificarCola',
        request_serializer=protocoloAtt__pb2.ColaRequest.SerializeToString,
        response_deserializer=protocoloAtt__pb2.ColaResponse.FromString,
        )
    self.AvisarDespegue = channel.unary_unary(
        '/Servicio/AvisarDespegue',
        request_serializer=protocoloAtt__pb2.DespegueRequest.SerializeToString,
        response_deserializer=protocoloAtt__pb2.DespegueResponse.FromString,
        )
    self.Atterizar = channel.unary_unary(
        '/Servicio/Atterizar',
        request_serializer=protocoloAtt__pb2.AterrizajeRequest.SerializeToString,
        response_deserializer=protocoloAtt__pb2.At_InstruccionesResponse.FromString,
        )
    self.VerificarCola_At = channel.unary_unary(
        '/Servicio/VerificarCola_At',
        request_serializer=protocoloAtt__pb2.At_ColaRequest.SerializeToString,
        response_deserializer=protocoloAtt__pb2.At_ColaResponse.FromString,
        )
    self.AvisarAterrizaje = channel.unary_unary(
        '/Servicio/AvisarAterrizaje',
        request_serializer=protocoloAtt__pb2.AterrizarRequest.SerializeToString,
        response_deserializer=protocoloAtt__pb2.AterrizarResponse.FromString,
        )


class ServicioServicer(object):
  """----------------------------------------------------

  service
  """

  def ConsultarDestino(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PedirPermiso(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PedirInstrucciones(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerificarCola(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AvisarDespegue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Atterizar(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerificarCola_At(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AvisarAterrizaje(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServicioServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ConsultarDestino': grpc.unary_unary_rpc_method_handler(
          servicer.ConsultarDestino,
          request_deserializer=protocoloAtt__pb2.NuevoAvionRequest.FromString,
          response_serializer=protocoloAtt__pb2.NuevoAvionResponse.SerializeToString,
      ),
      'PedirPermiso': grpc.unary_unary_rpc_method_handler(
          servicer.PedirPermiso,
          request_deserializer=protocoloAtt__pb2.PermisoRequest.FromString,
          response_serializer=protocoloAtt__pb2.PermisoResponse.SerializeToString,
      ),
      'PedirInstrucciones': grpc.unary_unary_rpc_method_handler(
          servicer.PedirInstrucciones,
          request_deserializer=protocoloAtt__pb2.InstruccionesRequest.FromString,
          response_serializer=protocoloAtt__pb2.InstruccionesResponse.SerializeToString,
      ),
      'VerificarCola': grpc.unary_unary_rpc_method_handler(
          servicer.VerificarCola,
          request_deserializer=protocoloAtt__pb2.ColaRequest.FromString,
          response_serializer=protocoloAtt__pb2.ColaResponse.SerializeToString,
      ),
      'AvisarDespegue': grpc.unary_unary_rpc_method_handler(
          servicer.AvisarDespegue,
          request_deserializer=protocoloAtt__pb2.DespegueRequest.FromString,
          response_serializer=protocoloAtt__pb2.DespegueResponse.SerializeToString,
      ),
      'Atterizar': grpc.unary_unary_rpc_method_handler(
          servicer.Atterizar,
          request_deserializer=protocoloAtt__pb2.AterrizajeRequest.FromString,
          response_serializer=protocoloAtt__pb2.At_InstruccionesResponse.SerializeToString,
      ),
      'VerificarCola_At': grpc.unary_unary_rpc_method_handler(
          servicer.VerificarCola_At,
          request_deserializer=protocoloAtt__pb2.At_ColaRequest.FromString,
          response_serializer=protocoloAtt__pb2.At_ColaResponse.SerializeToString,
      ),
      'AvisarAterrizaje': grpc.unary_unary_rpc_method_handler(
          servicer.AvisarAterrizaje,
          request_deserializer=protocoloAtt__pb2.AterrizarRequest.FromString,
          response_serializer=protocoloAtt__pb2.AterrizarResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Servicio', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
